repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0
    hooks:
      - id: black-jupyter
        language_version: python3.10

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
      name: isort (python)

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [ '--max-line-length=88' ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
