[tool.poetry]
description = """Repository collecting all the work related to my Master's Thesis
on explainability of uncertainty in time series forecasting."""
authors = ["Yannick Funk <yannick.funk2@kit.edu>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
